work_dir: ~/AINoteWorkspace/cli_transcrib_note
secret: ~/AINoteWorkspace/cli_transcrib_note/resources/secret.yml
ffmpeg: ffmpeg
whisper_cpp_dir: ~/AINoteWorkspace/whisper.cpp
mlx_whisper_models_dir: ~/AINoteWorkspace/mlx-examples/models

graphs:
  - name: NewsFeed
    path: ~/Library/Mobile Documents/iCloud~md~obsidian/Documents/NewsFeed2

  - name: Note
    path: ~/Library/Mobile Documents/iCloud~md~obsidian/Documents/Note2

  - name: Trading
    path: ~/Library/Mobile Documents/iCloud~com~logseq~logseq/Documents/Trading

  - name: Test
    path: ~/AINoteWorkspace/cli_transcrib_note/news/Test